#!/bin/bash

# Dependencies: imagemagick, i3lock-color-git, scrot


# get path where the script is located
# its used for the lock icon
pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd`
popd > /dev/null

IMAGE=$(mktemp).png
#TEXT="`faker-cli -x phrase`"
FULLTEXT="`/home/tanuj/Code/build-quotesCatogories-Desktop-Debug/quotesCategories`" 
firstchar="`echo ${FULLTEXT:0:1}`"
TEXT="`echo ${FULLTEXT:1}`" 

LOCKICONREG="lock"
LOCKICONDARK="lockdark"

if [ "$firstchar" == "h" ];then #if hacker quote
	LOCKICONREG="lock"
	LOCKICONDARK="lockdark"
elif [ "$firstchar" == "i" ];then #if itcrowd quote
	LOCKICONREG="roundmoss"
	LOCKICONDARK="roundmoss"
elif [ "$firstchar" == "s" ];then #if starwars quote
	LOCKICONREG="jediwhite"
        LOCKICONDARK="vader"
elif [ "$firstchar" == "p" ];then #if potter quote
	LOCKICONREG="scarheadwhite"
        LOCKICONDARK="scarhead"
elif [ "$firstchar" == "l" ];then #if sherlock quote
        LOCKICONREG="pipewhite"
        LOCKICONDARK="pipe"
elif [ "$firstchar" == "m" ];then #if meme quote
        LOCKICONREG="garlicbright"
        LOCKICONDARK="garlicdark"
fi

# l10n support
case $LANG in
    fr_* ) TEXT="Entrez votre mot de passe" ;; # Français
    es_* ) TEXT="Ingrese su contraseña" ;; # Española
    pl_* ) TEXT="Podaj hasło" ;; # Polish
esac

VALUE="60" #brightness value to compare to
scrot $IMAGE
COLOR=`convert $IMAGE -colorspace hsb -resize 1x1 txt:- | sed -E '/.*$/ {
                             N
                             s/.*\n.*([0-9]{1,2}[^\.])\.[0-9]+%\)$/\1/
                             }'`;
# pixelate: -scale 10% -scale 1000%
# sigma was 1.5

if [ "$COLOR" -gt "$VALUE" ]; then #white background image and black text
    convert $IMAGE -level 0%,100%,0.6 \
        -filter Gaussian -resize 20% -define filter:sigma=8.5 -resize 500.5% \
        -font Liberation-Sans -pointsize 32 -fill black  -gravity center \
        -annotate +0+160 "$TEXT" \
        $SCRIPTPATH/images/$LOCKICONDARK.png -gravity center -composite $IMAGE
    PARAM='--textcolor=00000000 --insidecolor=0ad65c1c --ringcolor=0000003e \
        --linecolor=00000000 --keyhlcolor=74e85888 --ringvercolor=ffffff00 \
        --insidevercolor=ffffff1c --ringwrongcolor=ffffff55 --insidewrongcolor=bf09095c'
else #black
    convert $IMAGE -level 0%,100%,0.6 \
        -filter Gaussian -resize 20% -define filter:sigma=8.5 -resize 500.5% \
        -font Liberation-Sans -pointsize 32 -fill white -gravity Center \
        -annotate +0+160 "$TEXT" \
        $SCRIPTPATH/images/$LOCKICONREG.png -gravity center -composite $IMAGE
    PARAM='--textcolor=ffffff00 --insidecolor=0ad65c6c --ringcolor=ffffff3e \
        --linecolor=ffffff00 --keyhlcolor=74e85888 --ringvercolor=00000000 \
        --insidevercolor=0000001c --ringwrongcolor=00000055 --insidewrongcolor=bf20151c'
fi

# try to use a forked version of i3lock with prepared parameters
i3lock $PARAM -i $IMAGE > /dev/null 2>&1

if [ $? -ne 0 ]; then
    # We have failed, lets get back to stock one
    i3lock -i $IMAGE
fi

rm $IMAGE
